
name: CD pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  DeployDev:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build, tag, and push image to Amazon ECR
      run: |
        # Build the Docker image
        docker build -t $ECR_REPOSITORY:$IMAGE_TAG .

        # Tag the Docker image
        docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REPOSITORY:latest

        # Push the Docker image to ECR
        docker push $ECR_REPOSITORY:$IMAGE_TAG
    - name: Deploy to App Runner
      uses: aws-actions/app-runner-deploy@master
      with:
        service-name: ${{ secrets.APP_RUNNER_SERVICE_NAME_DEV }}
        image-url: ${{ steps.login-ecr.outputs.image-url }}
        access-role-arn: ${{ secrets.APP_RUNNER_ACCESS_ROLE_ARN_DEV }}
        region: ${{ secrets.AWS_REGION }}
        cpu: 256
        memory: 512
        port: 80
        wait-for-service-stability: true
    - name: App Runner output
      run: echo "App Runner URL: ${{ steps.deploy.outputs.url }}"

  DeployPreProd:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PREPROD }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PREPROD }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build, tag, and push image to Amazon ECR
      run: |
        # Build the Docker image
        docker build -t $ECR_REPOSITORY:$IMAGE_TAG .

        # Tag the Docker image
        docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REPOSITORY:latest

        # Push the Docker image to ECR
        docker push $ECR_REPOSITORY:$IMAGE_TAG
    - name: Deploy to App Runner
      uses: aws-actions/app-runner-deploy@master
      with:
        service-name: ${{ secrets.APP_RUNNER_SERVICE_NAME_PREPROD }}
        image-url: ${{ steps.login-ecr.outputs.image-url }}
        access-role-arn: ${{ secrets.APP_RUNNER_ACCESS_ROLE_ARN_PREPROD }}
        region: ${{ secrets.AWS_REGION }}
        cpu: 256
        memory: 512
        port: 80
        wait-for-service-stability: true
    - name: App Runner output
      run: echo "App Runner URL: ${{ steps.deploy.outputs.url }}"

  DeployProd:
    if: github.ref == 'refs/heads/main'
    runs-