
name: Deploy to AWS App Runner

on:
  push:
    branches:
      - newui_master
  pull_request:
    branches:
      - newui_master

jobs:
  DeployDev:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build, tag, and push image to Amazon ECR
      run: |
        $(aws ecr get-login --no-include-email --region ${{ secrets.AWS_REGION }})
        IMAGE_TAG=${{ github.sha }}
        ECR_REGISTRY=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${AWS_REGION}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}
        docker build -t ${ECR_REGISTRY}:${IMAGE_TAG} .
        docker push ${ECR_REGISTRY}:${IMAGE_TAG}
    - name: Deploy to App Runner
      uses: aws-actions/app-runner-deploy@v1
      with:
        image-url: ${{ steps.login-ecr.outputs.image-url }}
        service-name: ${{ secrets.SERVICE_NAME_DEV }}
        access-role-arn: ${{ secrets.ACCESS_ROLE_ARN }}
        region: ${{ secrets.AWS_REGION }}
        cpu: 256
        memory: 512
        port: 80
        wait-for-service-stability: true
    - name: App Runner output
      run: echo ${{ steps.deploy.outputs.status }}
  DeployPreProd:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/newui_master'
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build, tag, and push image to Amazon ECR
      run: |
        $(aws ecr get-login --no-include-email --region ${{ secrets.AWS_REGION }})
        IMAGE_TAG=${{ github.sha }}
        ECR_REGISTRY=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${AWS_REGION}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}
        docker build -t ${ECR_REGISTRY}:${IMAGE_TAG} .
        docker push ${ECR_REGISTRY}:${IMAGE_TAG}
    - name: Deploy to App Runner
      uses: aws-actions/app-runner-deploy@v1
      with:
        image-url: ${{ steps.login-ecr.outputs.image-url }}
        service-name: ${{ secrets.SERVICE_NAME_PREPROD }}
        access-role-arn: ${{ secrets.ACCESS_ROLE_ARN }}
        region: ${{ secrets.AWS_REGION }}
        cpu: 256
        memory: 512
        port: 80
        wait-for-service-stability: true
    - name: App Runner output
      run: echo