
name: Continuous Deployment to AWS App Runner

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  DeployDev:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build, tag, and push image to Amazon ECR
      id: build-tag-push
      run: |
        # Build the Docker image
        docker build -t $ECR_REPOSITORY .

        # Tag the Docker image
        docker tag $ECR_REPOSITORY:latest $ECR_REPOSITORY:$IMAGE_TAG

        # Push the Docker image to Amazon ECR
        docker push $ECR_REPOSITORY:$IMAGE_TAG
    - name: Deploy to App Runner
      id: deploy-app-runner
      if: steps.build-tag-push.outputs.image-url
      uses: aws-actions/deploy-to-app-runner@v1
      with:
        image-url: ${{ steps.build-tag-push.outputs.image-url }}
        service-name: ${{ secrets.DEV_SERVICE_NAME }}
        access-role-arn: ${{ secrets.DEV_ACCESS_ROLE_ARN }}
        region: ${{ secrets.AWS_REGION }}
        cpu: 256
        memory: 512
        port: 80
        wait-for-service-stability: true
    - name: App Runner output
      id: app-runner-output
      if: steps.deploy-app-runner.outputs.status
      run: echo "App Runner status: ${{ steps.deploy-app-runner.outputs.status }}"

  DeployPreProd:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build, tag, and push image to Amazon ECR
      id: build-tag-push
      run: |
        # Build the Docker image
        docker build -t $ECR_REPOSITORY .

        # Tag the Docker image
        docker tag $ECR_REPOSITORY:latest $ECR_REPOSITORY:$IMAGE_TAG

        # Push the Docker image to Amazon ECR
        docker push $ECR_REPOSITORY:$IMAGE_TAG
    - name: Deploy to App Runner
      id: deploy-app-runner
      if: steps.build-tag-push.outputs.image-url
      uses: aws-actions/deploy-to-app-runner@v1
      with:
        image-url: ${{ steps.build-tag-push.outputs.image-url }}
        service-name: ${{ secrets.PREPROD_SERVICE_NAME }}
        access-role-arn: ${{ secrets.PREPROD_ACCESS_ROLE_ARN }}
        region: ${{ secrets.AWS_REGION }}
        cpu: 256
        memory: 512
        port