
name: Deploy to AWS App Runner

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  DeployDev:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and push Docker image to ECR
      uses:aws-actions/amazon-ecr-container-registry-login@master
      with:
        registry: ${{ env.ECR_REPOSITORY }}

    - name: Build
      run: |
        docker build -t ${{ env.ECR_REPOSITORY }} .
        docker push ${{ env.ECR_REPOSITORY }}

    - name: Deploy to AWS App Runner
      if: github.event_name == 'pull_request'
      uses:aws-actions/aws-app-runner-deploy@master
      with:
        service-name: ${{ env.APPRUNNER_DEV_SERVICE }}
        image: ${{ env.ECR_REPOSITORY }}
        region: ${{ env.AWS_REGION }}
        account-id: ${{ env.AWS_ACCOUNT_ID }}

  DeployPreProd:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and push Docker image to ECR
      uses:aws-actions/amazon-ecr-container-registry-login@master
      with:
        registry: ${{ env.ECR_REPOSITORY }}

    - name: Build
      run: |
        docker build -t ${{ env.ECR_REPOSITORY }} .
        docker push ${{ env.ECR_REPOSITORY }}

    - name: Deploy to AWS App Runner
      if: github.ref == 'refs/heads/main'
      uses:aws-actions/aws-app-runner-deploy@master
      with:
        service-name: ${{ env.APPRUNNER_PREPROD_SERVICE }}
        image: ${{ env.ECR_REPOSITORY }}
        region: ${{ env.AWS_REGION }}
        account-id: ${{ env.AWS_ACCOUNT_ID }}

  DeployProd:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and push Docker image to ECR
      uses:aws-actions/amazon-ecr-container-registry-login@master
      with:
        registry: ${{ env.ECR_REPOSITORY }}

    - name: Build
      run: |
        docker build -t ${{ env.ECR_REPOSITORY }} .
        docker push ${{ env.ECR_REPOSITORY }}

    - name: Deploy to AWS App Runner
      if: github.ref == 'refs/heads/main'
      uses:aws-actions/aws-app-runner-deploy@master
      with:
        service-name: ${{ env.APPRUNNER_PROD_SERVICE }}
        image: ${{ env.ECR_REPOSITORY }}
        region: ${{ env.AWS_REGION }}
        account-id: ${{ env.AWS_ACCOUNT_ID }}