
name: Deploy to AWS App Runner

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  DeployDev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push to development environment
      env:
        AWS_REGION: us-east-1
        AWS_ACCOUNT_ID: $
        ECR_REPOSITORY: my-repository
      run: |
        # Build and push to development environment
        docker build -t $ECR_REPOSITORY:latest .
        docker push $ECR_REPOSITORY:latest
        aws apprunner deploy-service --service-name app-runner-service-dev --region $AWS_REGION --image-tag latest --force-new-deployment
  DeployPreProd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push to staging environment
      env:
        AWS_REGION: us-east-1
        AWS_ACCOUNT_ID: $
        ECR_REPOSITORY: my-repository
      run: |
        # Build and push to staging environment
        docker build -t $ECR_REPOSITORY:latest .
        docker push $ECR_REPOSITORY:latest
        aws apprunner deploy-service --service-name app-runner-service-staging --region $AWS_REGION --image-tag latest --force-new-deployment
  DeployProd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push to production environment
      env:
        AWS_REGION: us-east-1
        AWS_ACCOUNT_ID: $
        ECR_REPOSITORY: my-repository
      run: |
        # Build and push to production environment
        docker build -t $ECR_REPOSITORY:latest .
        docker push $ECR_REPOSITORY:latest
        aws apprunner deploy-service --service-name app-runner-service-prod --region $AWS_REGION --image-tag latest --force-new-deployment